In [110]:
import numpy as np
import scipy.sparse as sparse
import scipy.linalg as la

def grad(f, x):
    '''
        Input:
            f: lambda function
            x: function args
        Output:
            grad_f: function gradient at x
    '''
    n = len(x)
    grad_f = np.zeros(n)
    
    E = np.diag([pow(np.finfo(float).eps, 1/3) * (abs(a) + 1) for a in x])
    
    for i in range(n):
        grad_f[i] = (f(x + E[:, i]) - f(x - E[:, i])) * (0.5 / E[i, i])
    
    return grad_f
    
def hess(f, x):
    '''
        Input:
            f: lambda function
            x: function args
        Output:
            hess_f: hessian of f at x
    '''
    n = len(x)
    hess_f = np.zeros([n, n])
    
    E = np.diag([pow(np.finfo(float).eps, 1/4) * (abs(a) + 1) for a in x])
    
    for i in range(n):
        for j in range(n):
            hess_f[i, j] = (  f(x + E[:, i] + E[:, j]) 
                            - f(x - E[:, i] + E[:, j]) 
                            - f(x + E[:, i] - E[:, j]) 
                            + f(x - E[:, i] - E[:, j]) ) * (0.25 / (E[i, i] * E[j, j]))
    
    return hess_f

def cyclic_coordinate_descent(x0, A, b, tol=1e-5, maxiter=1000):
    x = np.copy(x0)
    
    n = A.shape[0]
    m = 0
    k = 0
    r = A.dot(x) - b
    
    while la.norm(r, np.inf) > tol and (m*n + k) < maxiter:
        
        if k >= n:
            k = 0
            m = m + 1
        
        alpha = -r[k]/A[k, k]
        x[k] = x[k] + alpha
        r = A.dot(x) - b
        
        k += 1
        
    return x, m*n + k

In [83]:
A = sparse.diags([[2]*100, [1]*100, [1]*100], [0, -1, 1])
b = np.ones((100))

In [84]:
A

<100x100 sparse matrix of type '<class 'numpy.float64'>'
	with 298 stored elements (3 diagonals) in DIAgonal format>

In [85]:
b

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
[x, i] = cyclic_coordinate_descent(np.zeros(100), A.toarray(), b, maxiter = np.inf)

In [87]:
A.dot(x)

array([ 0.99999901,  1.00000148,  0.99999804,  1.00000243,  0.99999711,
        1.00000333,  0.99999625,  1.00000416,  0.99999545,  1.00000491,
        0.99999475,  1.00000557,  0.99999414,  1.00000613,  0.99999363,
        1.00000657,  0.99999325,  1.0000069 ,  0.99999299,  1.00000709,
        0.99999286,  1.00000716,  0.99999285,  1.0000071 ,  0.99999298,
        1.0000069 ,  0.99999324,  1.00000658,  0.99999363,  1.00000614,
        0.99999413,  1.00000558,  0.99999475,  1.00000491,  0.99999547,
        1.00000414,  0.99999628,  1.00000329,  0.99999717,  1.00000236,
        0.99999812,  1.00000138,  0.99999913,  1.00000035,  1.00000017,
        0.9999993 ,  1.00000124,  0.99999823,  1.0000023 ,  0.99999717,
        1.00000335,  0.99999613,  1.00000437,  0.99999513,  1.00000535,
        0.99999419,  1.00000626,  0.99999331,  1.0000071 ,  0.99999251,
        1.00000786,  0.99999181,  1.00000851,  0.99999121,  1.00000905,
        0.99999072,  1.00000948,  0.99999036,  1.00000978,  0.99

In [88]:
i

110791

In [111]:
B = np.array([[1, 0], [0, 3]])
d = np.array([1, 1])
x1 = np.array([-1, 3])

In [112]:
cyclic_coordinate_descent(x1, B, d, maxiter=10)

2.0
[1 3]
[0 8]
-2.66666666667
[1 0]
[ 0 -1]
0.0
[1 0]
[ 0 -1]
0.333333333333
[1 0]
[ 0 -1]
0.0
[1 0]
[ 0 -1]
0.333333333333
[1 0]
[ 0 -1]
0.0
[1 0]
[ 0 -1]
0.333333333333
[1 0]
[ 0 -1]
0.0
[1 0]
[ 0 -1]
0.333333333333
[1 0]
[ 0 -1]


(array([1, 0]), 10)

In [100]:
B.dot([3, 2])

array([3, 6])

In [101]:
B.dot(x1)

array([-1,  9])

In [108]:
B[1, 1]

3

In [109]:
B[1][1]

3